# Generated by Django 3.0.6 on 2023-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('Approoved', 'Approoved'), ('Rejected', 'Rejected'), ('Accepted Level 1', 'Accepted Level 1'), ('Submited', 'Submited')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Approoved', 'Approoved'), ('Rejected', 'Rejected'), ('Accepted Level 1', 'Accepted Level 1'), ('Submited', 'Submited')], max_length=1000, null=True),
        ),
    ]
