# Generated by Django 3.0.6 on 2023-04-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20230415_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='is_by_faculty',
            new_name='is_published_by_faculty',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='is_by_student',
            new_name='is_published_by_student',
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('Accepted Level 1', 'Accepted Level 1'), ('Submited', 'Submited'), ('Approoved', 'Approoved'), ('Rejected', 'Rejected')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Accepted Level 1', 'Accepted Level 1'), ('Submited', 'Submited'), ('Approoved', 'Approoved'), ('Rejected', 'Rejected')], max_length=1000, null=True),
        ),
    ]
