# Generated by Django 3.0.6 on 2023-04-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20230415_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('Rejected', 'Rejected'), ('Accepted Level 1', 'Accepted Level 1'), ('Approoved', 'Approoved'), ('Submited', 'Submited')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Rejected', 'Rejected'), ('Accepted Level 1', 'Accepted Level 1'), ('Approoved', 'Approoved'), ('Submited', 'Submited')], max_length=1000, null=True),
        ),
    ]
