# Generated by Django 3.0.6 on 2023-04-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20230416_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('Submited', 'Submited'), ('Accepted Level 1', 'Accepted Level 1'), ('Approoved', 'Approoved'), ('Rejected', 'Rejected')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Submited', 'Submited'), ('Accepted Level 1', 'Accepted Level 1'), ('Approoved', 'Approoved'), ('Rejected', 'Rejected')], max_length=1000, null=True),
        ),
    ]
