# Generated by Django 4.2 on 2023-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20230416_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('Request', 'Request'), ('Other', 'Other'), ('Documents', 'Documents'), ('Leave', 'Leave')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Rejected', 'Rejected'), ('Accepted Level 1', 'Accepted Level 1'), ('Submited', 'Submited'), ('Approoved', 'Approoved')], max_length=1000, null=True),
        ),
    ]
