# Generated by Django 3.0.6 on 2023-04-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_category_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('Leave', 'Leave'), ('Documents', 'Documents'), ('Other', 'Other'), ('Request', 'Request')], max_length=1000, null=True),
        ),
    ]
