# Generated by Django 3.0.6 on 2023-04-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Chemical', 'Chemical'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Textile', 'Textile'), ('Information Technology', 'Information Technology'), ('Production', 'Production'), ('Electronics', 'Electronics'), ('Computer Science', 'Computer Science')], max_length=300),
        ),
    ]
