# Generated by Django 3.0.6 on 2023-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0003_auto_20230415_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Production', 'Production'), ('Civil', 'Civil'), ('Chemical', 'Chemical'), ('Electronics', 'Electronics'), ('Information Technology', 'Information Technology'), ('Textile', 'Textile'), ('Computer Science', 'Computer Science'), ('Mechanical', 'Mechanical')], max_length=300),
        ),
    ]
