# Generated by Django 3.0.6 on 2023-04-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0004_auto_20230415_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Information Technology', 'Information Technology'), ('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Chemical', 'Chemical'), ('Production', 'Production'), ('Computer Science', 'Computer Science'), ('Textile', 'Textile')], max_length=300),
        ),
    ]
