# Generated by Django 3.0.6 on 2023-04-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0005_auto_20230415_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Computer Science', 'Computer Science'), ('Mechanical', 'Mechanical'), ('Production', 'Production'), ('Information Technology', 'Information Technology'), ('Chemical', 'Chemical'), ('Civil', 'Civil'), ('Textile', 'Textile')], max_length=300),
        ),
    ]
