# Generated by Django 3.0.6 on 2023-04-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0006_auto_20230416_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Civil', 'Civil'), ('Textile', 'Textile'), ('Computer Science', 'Computer Science'), ('Chemical', 'Chemical'), ('Production', 'Production'), ('Information Technology', 'Information Technology'), ('Mechanical', 'Mechanical')], max_length=300),
        ),
    ]
