# Generated by Django 4.2 on 2023-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0008_auto_20230416_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Chemical', 'Chemical'), ('Computer Science', 'Computer Science'), ('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Textile', 'Textile'), ('Production', 'Production')], max_length=300),
        ),
    ]
