# Generated by Django 3.0.6 on 2023-04-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_by_hod', models.BooleanField(default=False)),
                ('is_by_director', models.BooleanField(default=False)),
                ('is_for_department', models.BooleanField(default=False)),
                ('is_for_all_students', models.BooleanField(default=False)),
                ('is_for_all_faculties', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hod.department')),
                ('published_by_director', models.ForeignKey(limit_choices_to={'is_director': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('published_by_hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.hod')),
            ],
        ),
    ]
