# Generated by Django 3.0.6 on 2023-04-15 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=True)),
                ('is_hod', models.BooleanField(default=False)),
                ('is_director', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(choices=[('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Chemical', 'Chemical'), ('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science')], max_length=300)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('department_HOD', models.ForeignKey(blank=True, limit_choices_to={'is_faculty': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.department')),
                ('user', models.ForeignKey(limit_choices_to={'is_hod': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, choices=[('India', 'India')], default='India', max_length=10, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2nd Year', '2nd Year'), ('1st Year', '1st Year'), ('4th Year', '4th Year'), ('3rd Year', '3rd Year')], max_length=300)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.department')),
                ('user', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_by_hod', models.BooleanField(default=False)),
                ('is_by_director', models.BooleanField(default=False)),
                ('is_for_department', models.BooleanField(default=False)),
                ('is_for_all_students', models.BooleanField(default=False)),
                ('is_for_all_faculties', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.department')),
                ('published_by_director', models.ForeignKey(limit_choices_to={'is_director': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('published_by_hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.hod')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.department')),
                ('user', models.ForeignKey(limit_choices_to={'is_faculty': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Submited', 'Submited'), ('Rejected', 'Rejected'), ('Approoved', 'Approoved')], max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_by_faculty', models.BooleanField(default=False)),
                ('is_by_student', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.department')),
                ('published_by_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.faculty')),
                ('published_by_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
