# Generated by Django 3.0.6 on 2023-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20230415_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_rejected_by_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_rejected_by_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('Accepted Level 1', 'Accepted Level 1'), ('Rejected', 'Rejected'), ('Submited', 'Submited'), ('Approoved', 'Approoved')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Accepted Level 1', 'Accepted Level 1'), ('Rejected', 'Rejected'), ('Submited', 'Submited'), ('Approoved', 'Approoved')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Textile', 'Textile'), ('Chemical', 'Chemical'), ('Civil', 'Civil'), ('Computer Science', 'Computer Science'), ('Production', 'Production'), ('Information Technology', 'Information Technology'), ('Electronics', 'Electronics'), ('Mechanical', 'Mechanical')], max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=300),
        ),
    ]
