# Generated by Django 3.0.6 on 2023-04-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20230415_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dept',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='yer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
