# Generated by Django 3.0.6 on 2023-04-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20230416_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('2nd Year', '2nd Year'), ('4th Year', '4th Year'), ('1st Year', '1st Year'), ('3rd Year', '3rd Year')], max_length=300),
        ),
    ]
