# Generated by Django 4.2 on 2023-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20230416_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('3rd Year', '3rd Year'), ('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('4th Year', '4th Year')], max_length=300),
        ),
    ]
