# Generated by Django 3.0.6 on 2023-04-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('4th Year', '4th Year'), ('3rd Year', '3rd Year'), ('2nd Year', '2nd Year'), ('1st Year', '1st Year')], max_length=300),
        ),
    ]
